name: BreadStamp
options:
  bundleIdPrefix: com.parksinyoung
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"

targets:
  BreadStamp:
    type: application
    platform: iOS
    sources:
      - path: BreadStamp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: BreadStamp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.parksinyoung.breadstamp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
    info:
      path: BreadStamp/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: 빵도장
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: Background
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        NSLocationWhenInUseUsageDescription: "빵집 위치를 지도에 표시하기 위해 위치 권한이 필요합니다."
        NSCameraUsageDescription: "빵 사진을 촬영하기 위해 카메라 권한이 필요합니다."
        NSPhotoLibraryUsageDescription: "빵 사진을 선택하기 위해 사진 라이브러리 접근 권한이 필요합니다."

schemes:
  BreadStamp:
    build:
      targets:
        BreadStamp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
